### ISSUE TITLE
Make it easily possible to change colors

### ISSUE THREAD

**Issue by konsultaner** [rajeshwarpatlolla/ionic-datepicker#238]
Thanks for the awesome new features in the current release. I would like to see another one if possible. 

An easy way to change colors. These are two possibilities that would make it a lot easier for everyone:
1. put the css into scss to make it interoperable with any ionic build-chain
2. support for ionics color classes like balanced, assertive, etc.

Thank you!

**Comment by metric152** [comment]
I'm going to see if I can create a pull request that will add gulp-sass to the build process for the plugin. I can copy-paste the defaults into the header of the sass file.

**Comment by metric152** [comment]
It's actually easier to style the plugin through scss

add this to ionic.app.scss
@import "scss/date-picker";

add the contents below to the file: scss/_date-picker.scss
```scss
// Master color
$popup-color: $positive;

.ionic_datepicker_popup{
    // Style the buttons at the bottom
    .popup-buttons{
        button{
            background-color: $popup-color !important;
        }
    }
    // Style the body
    .popup-body{
        // Style the outline for today
        .today{
            border-color: $popup-color;
        }

        .selected_date{
            background-color: $popup-color;
        }

        // Style the header
        .selected_date_full{
            background-color: $popup-color !important;
        }

        // Style the arrow
        .button-clear{
            color: $popup-color !important;
        }

        // Style the month select
        .month_select, .year_select{
            border-color: $popup-color !important;

            // Style the arrow
            &::after{
                color: $popup-color !important;
            }
        }
    }
}
```
